= РТУ МИРЭА каф. Математики

Решение всех вариантов лабораторных работ для языка Си

== Структура

В директории `00` располагаются дополнительные файлы зависимостей. Файл `tests_main.cpp` основной файл запуска тестов.
Файл `base_macro.h` с базовыми макроопределениями, константами. Директория `catch2` это набор заголовочных
файлов для написания `unit` тестов, используется для проверки заданий.

== Проверка

== Ограничения

Код написан с некоторыми ограничениями. Из основных можно выделить компилиуемость основного кода решений по стандарту
языка `C90`, использования `C++` для написания `unit` тестов, использование сторонних `framework` для всего что не
относится к основному решению заданий.

Дополнительные ограничения:

. Использование функций стандартной библиотеки `scanf`, `fscanf` является моветоном и отсутствуют в коде решений. Хоть и
присутствуют иногда в коде примеров выполнения;
. Использование `cmake` в качестве утилиты описания проекта;
. Использования `UTF-8` в качестве основной кодировки. А также отсутствует явное выставление кодировки локали терминала;
.

== Оформление кода. Форматирование.

Весь код оформлен и отформатирован в соответствии с link:https://github.com/BasePractice/automata_programming/blob/develop/_1.CodeStyle/-1.CodeStyle.md[рекомендациями]

== Решения
. link:01/README.adoc[Задание №1]. Оригинал задания link:Задания/Lab_C_1_series.pdf[pdf]