= РТУ МИРЭА каф. Математики

Решение всех вариантов лабораторных работ для языка Си

== Структура

В директории `00` располагаются дополнительные файлы зависимостей. Файл `tests_main.cpp` основной файл запуска тестов.
Файл `base_macro.h` с базовыми макроопределениями, константами. Директория `catch2` это набор заголовочных
файлов для написания `unit` тестов, используется для проверки заданий.

== Проверка

== Ограничения

Код написан с некоторыми ограничениями. Из основных можно выделить компилиуемость основного кода решений по стандарту
языка `C90`, использования `C++` для написания `unit` тестов, использование сторонних `framework` для всего что не
относится к основному решению заданий.

Дополнительные ограничения:

. Использование функций стандартной библиотеки `scanf`, `fscanf` является моветоном и отсутствуют в коде решений. Хоть и
присутствуют иногда в коде примеров выполнения;
. Использование `cmake` в качестве утилиты описания проекта;
. Использования `UTF-8` в качестве основной кодировки. А также отсутствует явное выставление кодировки локали терминала;
.

== Оформление кода. Форматирование.

Весь код оформлен и отформатирован в соответствии с link:https://github.com/BasePractice/automata_programming/blob/develop/_1.CodeStyle/-1.CodeStyle.md[рекомендациями]

== Решения
. link:01/README.adoc[Задание №1]. Оригинал задания link:Задания/Lab_C_1_series.pdf[pdf]
. link:02/README.adoc[Задание №2]. Оригинал задания link:Задания/Lab_C_2_array.pdf[pdf]
. link:03/README.adoc[Задание №3]. Оригинал задания link:Задания/Lab_C_3_strings.pdf[pdf]
. link:04/README.adoc[Задание №4]. Оригинал задания link:Задания/Lab_C_4_Pointers.pdf[pdf]
. link:05/README.adoc[Задание №5]. Оригинал задания link:Задания/Lab_C_5_Sorting_Read-Write-Files.pdf[pdf]
. link:06/README.adoc[Задание №6]. Оригинал задания link:Задания/Lab_С_6_Multidimensional_arrays.pdf[pdf]
. link:07/README.adoc[Задание №7]. Оригинал задания link:Задания/Lab_C_7_List.pdf[pdf]
. link:09/README.adoc[Задание №9]. Оригинал задания link:Задания/Lab_C_9_Vararg.pdf[pdf]